version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    # directory where steps are run. Path must conform to the Go Workspace requirements
    working_directory: /go/src/github.com/civisanalytics/notebooks-arproxy

    environment:
      TEST_RESULTS: /tmp/test-results # path for circle to store test results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - restore_cache: # restores saved cache if no changes are detected since last run
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - v1-pkg-cache

      - run:
          name: Print Go version
          command: go version

      - run:
          name: Get JUnit reporter
          command: go get github.com/jstemmer/go-junit-report

      - run:
          name: Install linter
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.15.0
            bin/golangci-lint --version
      - run:
          name: Run linter
          command: bin/golangci-lint run ./... | tee ${TEST_RESULTS}/go-linters-output.out

      - save_cache: # Store cache in the /go/pkg directory
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results
